version: '2.3'
services:
  # To run benchmark suite docker-compose run --rm php src/benchmark
  php:
    build:
      context: ./env
      dockerfile: Dockerfile_ArangoDb_PHP_Driver
    environment:
      DRIVER: "arangodb"
      PHP_IDE_CONFIG: "serverName=application"
      ARANGODB_HOST: "vst://database:8529"
      ARANGODB_USERNAME: ""
      ARANGODB_PASSWORD: ""
      ARANGODB_DB: _system
    volumes:
      - "./:/app"
    #cpuset: phpcpuset
    #cpu_count: phpcpu_count
    #mem_limit: phpmem_limit
    #mem_reservation: phpmem_reservation

  database:
    image: arangodb:3.3
    ports:
      - 8529:8529
    environment:
      ARANGO_NO_AUTH: 1
      #ARANGO_STORAGE_ENGINE: rocksdb
    #cpuset: dbcpuset
    #cpu_count: dbcpu_count
    #mem_limit: dbmem_limit
    #mem_reservation: dbmem_reservation
